main: main.cpp
	echo ----------------compiling main.ccp to create executable program main--------------------
	g++ -ggdb -std=c++11 main.cpp -o main
clean:
	echo ----------------removing executable program main--------------------
	/bin/rm main
